version: '3'
services:
  stock-db:
    image: "mysql:5"
    container_name: stock-db
    ports:
      - 3306:3306
    volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=stock_price
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge